spring.datasource.url=jdbc:mysql://root:TdDHToSyzmXhbQEecEQQhTnkFaWmaBIp@switchyard.proxy.rlwy.net:39983/railway
spring.datasource.username=root
spring.datasource.password=TdDHToSyzmXhbQEecEQQhTnkFaWmaBIp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Optional: reduce noisy startup logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Static resource configuration
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/images/
spring.mvc.static-path-pattern=/**

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Multipart config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Increase payload constraints for base64 image uploads
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB
